### ISSUE TITLE
height에 transition 간단하게 적용하기

### ISSUE THREAD

**Issue by bicochan** [bicochan/dev-note#11]
```css
div {
  max-height: 0;
  transition: max-height 0.3s ease-in;
}
div.open {
  max-height: 100vh;
}
```

- height로 제어하려고 하면 dom이 로드될 때 각 요소의 height 값을 가져와 데이터에 담아둔 후 각 요소에 `height: 0`을 지정해줘야 함
  - `height: auto`는 transition 적용이 안 됨
